# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.runs/synth_1/Top_Thermostat.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.cache/wt [current_project]
set_property parent.project_path C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:basys3:part0:1.2 [current_project]
set_property ip_output_repo c:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog -library xil_defaultlib {
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/30min_driver.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/ANODE_DECODER.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/CATODE_DECODER.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/CLOCK_COUNTER.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/CNT_03.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/new/COUNTER_SS.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/new/Comms_Dispatcher.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/DB.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/DELTA_T_DRIVER.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/DIGIT_DECODER.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/DISPLAY_LED_DRIVER.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Dp_master_fifo.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Dp_slave_fifo.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/Driver_MANOR_CELLAR.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/FSM.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Fsm_master_fifo.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Fsm_slave.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/GetCharacter.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/LED_DRIVER.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/MUX_2.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/MUX_4.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/new/Master_buttons.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Master_fifo_display.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/REG.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/RT_DRIVER.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Ready_Gen.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/RomParam.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/SELECTOR_SYST_CORE.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/SEVEN_SEG_DRIVER.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/SPI_master.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/SPI_slave.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/SPI_top.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/START_DRIVERC.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/START_DRIVERM.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/SUB_SUM_DRIVER.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/SYSTEM_CORE_TOP_MODULE.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Selector_master_fifo.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Slave_7SD.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/new/Slave_buttons.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/Slave_fifo.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/TIMER.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/TOP_MODULE_CELLAR.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/TOP_MODULE_MANOR.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/TopModule.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/VAR_DRIVER.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/WINDOWS_OPEN_DRIVER.v}
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/WINDOWS_OPEN_DRIVERC.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/adapter_M.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/alarm_driver.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/boud_rate_clk_gen.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/clk_gen_M.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/contasec.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/counter.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/counter_UART.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/counter_std.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/decodeMessage.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/dp.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/fsm.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/fsmAL_REST.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/new/fsmCONF.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/fsm_SPI_master.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/fsm_logScreenConnection.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/fsm_modified.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/new/fsm_rele.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/modeAdapter.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/mux.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/orologio.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/ptr_mng.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/ramParam.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/register.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/state_machine.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/temp_hour.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/timer_param.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/top_FIFO.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/top_alarm.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/top_clk_gen_mode.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/top_slave_7SD.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/sources_1/imports/files/top_slave_fifo.v
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/files_log/top_tx.v
  {C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/imports/crazy mod/var_driver_selector.v}
  C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/sources_1/new/Top_Thermostat.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/constrs_1/imports/Desktop/BasysConstr.xdc
set_property used_in_implementation false [get_files C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/constrs_1/imports/Desktop/BasysConstr.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental C:/Universit/SEA_2/Assignment_2/TopModule_Thermostat/TopModule_Thermostat.srcs/utils_1/imports/synth_1/Top_Thermostat.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Top_Thermostat -part xc7a35tcpg236-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Thermostat.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Thermostat_utilization_synth.rpt -pb Top_Thermostat_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
